apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: felipemeamaral/goserver:v5.2
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 3
            failureThreshold: 1

          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8000
          #   periodSeconds: 5
          #   failureThreshold: 3
          #   timeoutSeconds: 1
          #   successThreshold: 1

          envFrom:
            - secretRef:
                name: goserver-secret
            - configMapRef:
                name: goserver-env

          volumeMounts:
            - mountPath: "/app/myfamily/"
              name: config

      volumes:
        - name: config
          configMap:
            name: goserver-family
            items:
            - key: members
              path: "family.txt"
              