apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: felipemeamaral/goserver:v5.4

          resources:
            requests:
              cpu: 100m
              memory: 20Mi
            limits:
              cpu: 500m
              memory: 40Mi

          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 8
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 10
            failureThreshold: 1
            # initialDelaySeconds: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 15
            failureThreshold: 3
            timeoutSeconds: 1
            successThreshold: 1
            # initialDelaySeconds: 15

          envFrom:
            - secretRef:
                name: goserver-secret
            - configMapRef:
                name: goserver-env

          volumeMounts:
            - mountPath: "/app/myfamily/"
              name: config
            - mountPath: "/go/pvc"
              name: goserver-pvc

      volumes:
        - name: goserver-pvc
          persistentVolumeClaim:
            claimName: goserver-pvc

        - name: config
          configMap:
            name: goserver-family
            items:
            - key: members
              path: "family.txt"
              