apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  serviceName: goserver
  replicas: 10
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        image: felipemeamaral/goserver:v1

